services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    command: tail -f /dev/null

  selenoid:
    build:
      context: .
      dockerfile: Dockerfile.selenoid
    ports:
      - "4444:4444"