services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    command: tail -f /dev/null  # Держим контейнер активным

  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/selenoid/config:/etc/selenoid:ro
  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    environment:
      - SELENOID_URI=http://selenoid:4444
    volumes:
      - /path/to/selenoid-ui/config:/etc/selenoid-ui:ro